FROM node:20-alpine
WORKDIR /app
COPY backend/package.json backend/package-lock.json ./
COPY backend/prisma ./prisma
RUN npm install
COPY backend/ ./
RUN npm run build
EXPOSE 5000
CMD ["node", "dist/main.js"]
